//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class DeadlyThings
{

	[Flags]
	public enum Types
	{
        pistol = 2 * 4096,
		revolver = 1,
		shotgun = 2,
		spas = 4,
		uzi = 8,
		assault = 16,
		barret = 32,
		dynamite = 64,
		mine = 128,
		axe_rusty = 256,
		axe_double = 512,
		axe_fire = 1024,
		chainsaw = 2048,
		treefall = 4096
	}

	public static Types EXPLOSIVES = Types.dynamite | Types.mine;
	public static Types ANY_GUN = Types.pistol | Types.revolver | Types.shotgun | Types.spas | Types.assault | Types.barret | Types.uzi;
	public static Types MELEE = Types.axe_rusty | Types.axe_fire | Types.chainsaw | Types.axe_double;	
	public static Types ANY = EXPLOSIVES | ANY_GUN | MELEE | Types.treefall;
	public static Types AXES = Types.axe_rusty | Types.axe_fire | Types.axe_double;
}




