//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class GunData : WeaponData
{
	public enum Mode{
		auto,
		semi
	}

	public int ammo_max;
	public int ammo_current;
	public float reload_time;
	public float rate;
	public Mode mode = Mode.semi;
	public float dispersion;
	public int fragments;
	public int damage_min;
	public int damage_max;
	public float force;
	public float recoilPerShot;
	public float recoilReduction;

	public float reload_time_left;


}


