//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Weapon
{
    protected DeadlyThings.Types relatedTypes;
	protected int rayCastDistance;
    public SpriteRenderer renderer;

	public virtual void ManualUpdate(Vector2 pivotScreenPosition, Vector2 pivotPositionm){
	}

	public virtual void SetWeapon(WeaponData wd){
	}



}


