//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Weapon : MonoBehaviour
{

    [EnumFlagsAttribute]
    public DeadlyThings.Types RelatedTypes;
	public int RayCastDistance;
    public SpriteRenderer Renderer;
    public Animator Animator;
    public Lumberjack Lumberjack;

	public virtual void SetWeapon(WeaponData wd){
	}
      
	public virtual void Kill ()
	{
        gameObject.SetActive(false);
	}

	public virtual void Init ()
	{
        gameObject.SetActive(true);
	}

    public virtual T GetData<T>() where T:WeaponData 
    {
        return null;
    }

}


