//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Weapon
{
    public DeadlyThings.Types relatedTypes;
	protected int rayCastDistance;
    protected SpriteRenderer renderer;
	protected Animator animator;

	public virtual void ManualUpdate(Vector2 pivotScreenPosition, Vector2 pivotPosition){
	}

	public virtual void SetWeapon(WeaponData wd){
	}

	public Weapon(GameObject parent){
		renderer = parent.GetComponent<SpriteRenderer>();
		animator = parent.GetComponent<Animator>();
	}

	public virtual void Kill ()
	{
	}

	public virtual void Init ()
	{
	}
}


